; Generated by goyangi Compiler.

; compile the program using commands like:
;	fasm [output code].asm [output object].o

format ELF



section '.text' executable

	public main
	main:

	extrn printf
	extrn scanf
begin_0:
	PUSH	[numero]
	PUSH	int_mask
	CALL	printf
	PUSH	str_2
	PUSH	string_mask
	CALL	printf
	PUSH	[numero]
	PUSH	int_mask
	CALL	printf
	PUSH	numero
	PUSH	int_mask
	CALL	scanf
	MOV	EAX, [numero]
	MOV	EBX, 3
	CMP	EAX, EBX
	JNL	else_1
	PUSH	str_3
	PUSH	string_mask
	CALL	printf
	JMP	end_1
else_1:
	PUSH	str_4
	PUSH	string_mask
	CALL	printf
end_1:
	PUSH	[numero]
	PUSH	int_mask
	CALL	printf
end_0:
	mov	EAX, 1
	XOR	EBX, EBX
	INT	0x80

section '.data' writeable

string_mask	db	"%s", 0
int_mask  	db	"%d", 0
str_2     	db	"Digite numero", 0xA, 0
str_3     	db	"Menor que 3.", 0xA, 0
str_4     	db	"Maior ou igual a 3.", 0xA, 0
numero    	dd	0
