productions = {
        0: ['begin' ,'<STMT_LIST>','end'],
        1: ['<STMT>','<STMT_LIST>'],
        2: ['î']    ,
        3: ['<WRITE>'],
        4: ['<READ>'],
        5: ['<CONDITION>'],
        6: ['<LOOP>'],
        7: ['<DECLARE>'],
        8: ['<ATTRIBUTION>'],
        9: ['write','tk_openparenthesis','<OTHER_EXP>','tk_closeparenthesis','tk_semicolon'],
        10:['read','tk_openparenthesis','id','tk_closeparenthesis','tk_semicolon'],
        11:['<IF>','<ELSE>','end'],
        12:['if','tk_openparenthesis','<EXP>','tk_closeparenthesis','tk_colon','<STMT_LIST>'],
        13:['else','tk_colon','<STMT_LIST>'],
        14:['î'],
        15:['<WHILE>','end'],
        16:['while','tk_openparenthesis','<EXP>','tk_closeparenthesis','tk_colon','<STMT_LIST>'],
        17:['int','id','tk_semicolon'],
        18:['id','tk_assign','<EXP>','tk_semicolon'],
        19:['id','<EXP_OP>'],
        20:['integer','<EXP_OP>'],
        21:['tk_openparenthesis','<EXP_OP>','tk_closeparenthesis','<EXP_OP>'],
        22:['string','<STR_OP>'],
        23:['+','<STR_EXP>'],
        24:['î'],
        25:['<EXP>'],
        26:['<STR_EXP>'],
        27:['+','<EXP>'],
        28:['-','<EXP>'],
        29:['*','<EXP>'],
        30:['/','<EXP>'],
        31:['<','<EXP>'],
        32:['>','<EXP>'],
        33:['=','<EXP>'],
        34:['î'],
}